# CI on Windows via appveyor
# This file was based on Olivier Grisel's python-appveyor-demo
branches:
  except:
    - fix-docs

environment:

  matrix:
    - PYTHON: "C:\\Python27-conda32"
      PYTHON_VERSION: "2.7"
      PYTHON_ARCH: "32"
      CONDA_ENV: "py27-windows"

    - PYTHON: "C:\\Python27-conda64"
      PYTHON_VERSION: "2.7"
      PYTHON_ARCH: "64"
      CONDA_ENV: "py27-windows"

    - PYTHON: "C:\\Python36-conda64"
      PYTHON_VERSION: "3.6"
      PYTHON_ARCH: "64"
      CONDA_ENV: "py36-windows"

install:
  # Install miniconda Python
  - "powershell ./ci/install_python.ps1"

  # Prepend newly installed Python to the PATH of this build (this cannot be
  # done from inside the powershell script as it would require to restart
  # the parent CMD process).
  - "SET PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%"

  # install xarray and dependencies
  - "conda env create --file ./ci/requirements-%CONDA_ENV%.yml"
  - "activate test_env"
  - "conda list"
  - "python setup.py install"
  - "python xarray/util/print_versions.py"

build: false

test_script:
  - "py.test xarray --verbose"
