name: datatree-test
channels:
  - conda-forge
  - nodefaults
dependencies:
  - python>=3.8
  - xarray>=0.20.2
  - netcdf4
  - anytree
  - pytest
  - flake8
  - black
  - codecov
  - pytest-cov
  - h5netcdf
  - zarr
