name: xarray-docs
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.5
  - numpy=1.11.2
  - pandas=0.21.0
  - numpydoc=0.7.0
  - matplotlib=2.0.0
  - seaborn=0.8
  - dask=0.16.0
  - ipython=6.2.1
  - sphinx=1.5
  - netCDF4=1.3.1
  - cartopy=0.15.1
  - rasterio=0.36.0
  - sphinx-gallery
  - zarr
  - iris
  - flake8
